### ISSUE TITLE
Inputs names for nested arrays?

### ISSUE THREAD

**Issue by thanosalexander** [micheleangioni/multi-language#3]
what name do we have to give to an input that is in nested array? 
eg
```
'car'=>[
   'sport'=>'Sport',
   'jeep'=>'Jeep',
   'sedan'=>'Sedan'
]

```

Using . or _ notation , it saves it as car_sport,car_jeep and car_sedan in root level of translation file and not as it was.(nested array). The name of input i have in the form now is car.sport, but i tried car[sport] too and car_sport also but same issue!

**Comment by micheleangioni** [comment]
Hi,
the `writeLanguageFile($fileName, array $inputs)` method required an input array with dot notation.

Take a look at the [tests](https://github.com/micheleangioni/multi-language/blob/master/tests/LanguageManagerTest.php)

```php
[...]
$inputs = array (
    'key1.key11' => 'value11',
    'key1.key12' => 'value12',
    'key2' => 'value2',
    'key3.key31' => 'value31',
    'key3.key32' => 'value32',
    'key4.key41.key42' => 'value42',
);

[...]

$result = $languageManager->writeLanguageFile($fileName, $inputs);
```

If you have a nested array, you first need to use the `convertArrayToDotNotation(array $array)` method and then pass the resulting array to the `writeLanguageFile()` method.

Hope this helps!

**Comment by thanosalexander** [comment]
thanks! it solved the problem!!

**Comment by micheleangioni** [comment]
Glad to hear that :)
